const slugMap: Record<string, string> = {
  react: "react",
  typescript: "typescript",
  "next.js": "nextdotjs",
  nextjs: "nextdotjs",
  "tailwind css": "tailwindcss",
  tailwindcss: "tailwindcss",
  "framer motion": "framer",
  "node.js": "nodedotjs",
  nodejs: "nodedotjs",
  postgresql: "postgresql",
  figma: "figma",
  "three.js": "threedotjs",
  threejs: "threedotjs",
  graphql: "graphql",
  docker: "docker",
  aws: "amazonaws",
  git: "git",
  python: "python",
  mongodb: "mongodb",
  javascript: "javascript",
  vue: "vuedotjs",
  "vue.js": "vuedotjs",
  angular: "angular",
  svelte: "svelte",
  rust: "rust",
  go: "go",
  java: "java",
  "c++": "cplusplus",
  "c#": "csharp",
  swift: "swift",
  kotlin: "kotlin",
  firebase: "firebase",
  supabase: "supabase",
  redis: "redis",
  mysql: "mysql",
  sass: "sass",
  css: "css3",
  html: "html5",
  linux: "linux",
  github: "github",
  gitlab: "gitlab",
  vercel: "vercel",
  netlify: "netlify",
  prisma: "prisma",
  express: "express",
  django: "django",
  flask: "flask",
  ruby: "ruby",
  php: "php",
  wordpress: "wordpress",
  shopify: "shopify",
  stripe: "stripe",
};

export function getSkillIconUrl(skillName: string): string {
  const slug =
    slugMap[skillName.toLowerCase()] || skillName.toLowerCase().replace(/[.\s]/g, "");
  return `https://cdn.simpleicons.org/${slug}/ffffff`;
}
